# Generated by Django 5.0.8 on 2024-09-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='isbn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='publisher',
            field=models.TextField(null=True),
        ),
    ]
