# Generated by Django 4.2.7 on 2023-11-22 16:29

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0001_create_hstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('canonical_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_agents', to='collector.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('last_harvested', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('oai_set', models.CharField(blank=True, max_length=64)),
                ('oai_metadata_format', models.CharField(choices=[('oai_dc', 'Dublin Core'), ('marc21', 'MARC XML')], default='oai_dc', max_length=32)),
                ('site_type', models.CharField(choices=[('amusewiki', 'Amusewiki'), ('generic', 'Generic')], default='generic', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('author', 'Author'), ('subject', 'Subject'), ('language', 'Language')], max_length=32)),
                ('value_name', models.CharField(max_length=255)),
                ('value_canonical', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.site')),
            ],
            options={
                'verbose_name_plural': 'Name Aliases',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('logs', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.site')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('year_edition', models.IntegerField(null=True)),
                ('year_first_edition', models.IntegerField(null=True)),
                ('checksum', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(related_name='authored_entries', to='collector.agent')),
                ('canonical_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_entries', to='collector.entry')),
                ('languages', models.ManyToManyField(to='collector.language')),
                ('subjects', models.ManyToManyField(to='collector.subject')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oai_pmh_identifier', models.CharField(max_length=2048)),
                ('datetime', models.DateTimeField()),
                ('full_data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('uri', models.URLField(max_length=2048, null=True)),
                ('uri_label', models.CharField(max_length=2048, null=True)),
                ('content_type', models.CharField(max_length=128, null=True)),
                ('material_description', models.TextField(null=True)),
                ('shelf_location_code', models.CharField(max_length=255, null=True)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.entry')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='namealias',
            constraint=models.UniqueConstraint(fields=('site', 'field_name', 'value_name'), name='unique_site_field_name_value_name'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(fields=('site', 'oai_pmh_identifier'), name='unique_site_oai_pmh_identifier'),
        ),
    ]
