# Generated by Django 4.2.7 on 2023-11-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='full_data',
            field=models.JSONField(),
        ),
    ]
