# Generated by Django 5.0.8 on 2024-09-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_datasource_isbn_datasource_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='library',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='library',
            name='logo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='year_established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='csv_type',
            field=models.CharField(blank=True, choices=[('calibre', 'Calibre'), ('abebooks_home_base', 'Abebooks Home Base'), ('disordine', 'Biblioteca Disordine')], max_length=32, null=True),
        ),
    ]
