# Generated by Django 4.2.7 on 2023-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_datasource_full_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
