# Generated by Django 5.0.8 on 2024-09-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_library_description_library_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='address_city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='library',
            name='address_country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='library',
            name='address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='library',
            name='address_state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='library',
            name='address_zip',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='library',
            name='pgp_public_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='library',
            name='short_desc',
            field=models.TextField(blank=True),
        ),
    ]
