# Generated by Django 5.0.8 on 2024-09-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_library_address_city_library_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_type',
            field=models.CharField(choices=[('physical', 'Physical Library'), ('digital', 'Digital Library'), ('closed', 'Closed or Private Library')], max_length=32, null=True),
        ),
    ]
