# Generated by Django 5.0.8 on 2024-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_library_library_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='viaf_identifier',
            field=models.BigIntegerField(null=True),
        ),
    ]
