# Generated by Django 5.0.8 on 2024-10-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_remove_agent_description_agent_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='object_data',
            field=models.JSONField(null=True),
        ),
    ]
