# Generated by Django 5.0.8 on 2024-10-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_changelog_object_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'verbose_name_plural': 'Changelogs'},
        ),
    ]
