# Generated by Django 5.0.8 on 2025-01-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_page_language_page_location_page_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='edition_statement',
            field=models.TextField(null=True),
        ),
    ]
