# Generated by Django 4.2.7 on 2024-01-06 10:06

from django.db import migrations
from urllib.parse import urlparse

def populate_libraries(apps, schema_editor):
    Site = apps.get_model("collector", "Site")
    Library = apps.get_model("collector", "Library")
    for site in Site.objects.filter(library=None):
        base = urlparse(site.url)
        url = "{0}://{1}".format(base.scheme, base.hostname)
        try:
            lib = Library.objects.get(url=url)
        except Library.DoesNotExist:
            lib = Library.objects.create(url=url, name=site.title)
        site.library = lib
        site.save()

class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_library_site_library'),
    ]

    operations = [
        migrations.RunPython(populate_libraries)
    ]
