# Generated by Django 5.0.8 on 2025-01-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_datasource_edition_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='place_date_of_publication_distribution',
            field=models.TextField(null=True),
        ),
    ]
