# Generated by Django 4.2.7 on 2024-01-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20240106_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='collector.library'),
        ),
    ]
