# Generated by Django 5.0.8 on 2025-01-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_datasource_place_date_of_publication_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('sent', models.DateTimeField(null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.library')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
