# Generated by Django 4.2.7 on 2024-01-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_alter_library_url_alter_site_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterField(
            model_name='library',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='oai_metadata_format',
            field=models.CharField(choices=[('oai_dc', 'Dublin Core'), ('marc21', 'MARC XML')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='oai_set',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('amusewiki', 'Amusewiki'), ('generic', 'Generic OAI-PMH'), ('csv', 'CSV Upload')], default='generic', max_length=32),
        ),
    ]
