# Generated by Django 4.2.7 on 2024-01-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_alter_library_options_alter_library_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusion',
            name='exclude_site',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sites',
        ),
        migrations.AddField(
            model_name='exclusion',
            name='exclude_library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.library'),
        ),
        migrations.AddField(
            model_name='library',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='library',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='libraries',
            field=models.ManyToManyField(to='collector.library'),
        ),
    ]
