# Generated by Django 4.2.7 on 2024-01-06 15:14

from django.db import migrations

def update_library_booleans(apps, schema_editor):
    Site = apps.get_model("collector", "Site")
    for site in Site.objects.all():
        library = site.library
        library.public = site.public
        library.active = site.active
        library.save()

class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_remove_exclusion_exclude_site_remove_profile_sites_and_more'),
    ]

    operations = [
        migrations.RunPython(update_library_booleans)
    ]
