# Generated by Django 5.1.6 on 2025-02-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0015_alter_site_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='normalized_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
