# Generated by Django 5.1.6 on 2025-02-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_agent_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='last_indexed',
            field=models.DateTimeField(null=True),
        ),
    ]
