# Generated by Django 4.2.7 on 2024-01-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0016_update_library_booleans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='public',
        ),
    ]
