# Generated by Django 4.2.7 on 2024-01-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_remove_site_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='year_edition',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='year_first_edition',
        ),
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='year_edition',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='year_first_edition',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='namealias',
            name='field_name',
            field=models.CharField(choices=[('author', 'Author'), ('title', 'Title'), ('subtitle', 'Subtitle'), ('language', 'Language')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
