# Generated by Django 5.1.6 on 2025-04-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_entry_last_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryerrorreport',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.library'),
        ),
    ]
