# Generated by Django 5.1.6 on 2025-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_alter_libraryerrorreport_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
