# Generated by Django 5.0.1 on 2024-02-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_remove_entry_description_remove_entry_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='is_aggregation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_aggregation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spreadsheetupload',
            name='csv_type',
            field=models.CharField(choices=[('calibre', 'Calibre'), ('abebooks_home_base', 'Abebooks Home Base')], max_length=32),
        ),
        migrations.CreateModel(
            name='AggregationDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_pos', models.IntegerField(null=True)),
                ('aggregated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_data_sources', to='collector.datasource')),
                ('aggregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_data_sources', to='collector.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='AggregationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_entries', to='collector.entry')),
                ('aggregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_entries', to='collector.entry')),
            ],
            options={
                'verbose_name_plural': 'Aggregation Entries',
            },
        ),
        migrations.AddConstraint(
            model_name='aggregationdatasource',
            constraint=models.UniqueConstraint(fields=('aggregation', 'aggregated'), name='unique_data_source_aggregation_aggregated'),
        ),
        migrations.AddConstraint(
            model_name='aggregationentry',
            constraint=models.UniqueConstraint(fields=('aggregation', 'aggregated'), name='unique_entry_aggregation_aggregated'),
        ),
    ]
