# Generated by Django 5.1.6 on 2025-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_agent_wikidata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='place_of_death',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='viaf_identifier',
        ),
        migrations.AddField(
            model_name='agent',
            name='children',
            field=models.ManyToManyField(related_name='collapsed_agents', to='collector.agent'),
        ),
        migrations.AlterField(
            model_name='site',
            name='csv_type',
            field=models.CharField(blank=True, choices=[('calibre', 'Calibre'), ('abebooks_home_base', 'Abebooks Home Base'), ('disordine', 'Biblioteca Disordine'), ('belladonna', 'Biblioteca Belladonna')], max_length=32, null=True),
        ),
    ]
