# Generated by Django 5.0.1 on 2024-03-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_add_aggregation_rels'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='has_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='has_raw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='has_text',
            field=models.BooleanField(default=False),
        ),
    ]
