# Generated by Django 5.2.3 on 2025-07-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_remove_agent_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='active',
            field=models.BooleanField(default=True, help_text='If not checked, the catalog is not accessible at all'),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_type',
            field=models.CharField(choices=[('physical', 'Physical Library, always listed'), ('digital', 'Digital Library, listed only if public'), ('closed', 'Closed or Private Library, listed only if public')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='public',
            field=models.BooleanField(default=False, help_text='If not checked, the catalog is accessible only to authenticated users'),
        ),
    ]
