# Generated by Django 5.0.1 on 2024-04-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_add_changelogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='has_print',
        ),
    ]
