# Generated by Django 5.2.3 on 2025-07-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_alter_library_active_alter_library_library_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='name',
            field=models.CharField(choices=[('site_name', 'Site Name'), ('site_logo', 'Site Logo'), ('site_description', 'Site Description'), ('contact_email', 'Contact Email')], max_length=32, unique=True),
        ),
    ]
