# Generated by Django 5.2.3 on 2025-08-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_alter_general_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='logged_in_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='location',
            field=models.CharField(choices=[('draft', 'Drafts'), ('footer', 'Footer'), ('user_menu', 'User Menu')], default='draft', max_length=16),
        ),
    ]
