# Generated by Django 5.0.1 on 2024-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0022_remove_site_has_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='datetime',
        ),
        migrations.AddField(
            model_name='datasource',
            name='datestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='datestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
