# Generated by Django 5.2.3 on 2025-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_page_logged_in_only_alter_page_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('ALL', 'All Languages'), ('bg', 'Български'), ('cs', 'Čeština'), ('da', 'Dansk'), ('de', 'Deutsch'), ('el', 'Ελληνικά'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Español'), ('eu', 'Euskara'), ('fa', 'فارسی'), ('fi', 'Suomi'), ('fr', 'Français'), ('hr', 'Hrvatski'), ('hu', 'Magyar'), ('id', 'Bahasa Indonesia'), ('it', 'Italiano'), ('ja', '日本語'), ('mk', 'Македонски'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('pt', 'Português'), ('ro', 'Română'), ('ru', 'Русский'), ('sq', 'Shqip'), ('sr', 'Srpski'), ('sv', 'Svenska'), ('tl', 'Tagalog'), ('tr', 'Türkçe'), ('uk', 'Українська'), ('zh', '中文')], default='en', max_length=4),
        ),
    ]
