# Generated by Django 5.2.3 on 2025-08-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_alter_page_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='shelf_location_code',
            field=models.TextField(null=True),
        ),
    ]
