# Generated by Django 5.0.1 on 2024-07-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_password_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admin_library',
        ),
        migrations.AddField(
            model_name='library',
            name='check_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='library',
            name='email_internal',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='library',
            name='email_public',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='library',
            name='enable_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='library',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='opening_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='library',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='library_admin',
            field=models.BooleanField(default=False),
        ),
    ]
