# Generated by Django 5.2.3 on 2025-10-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_alter_datasource_shelf_location_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='is_aggregation',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='is_aggregation',
        ),
        migrations.AlterField(
            model_name='site',
            name='csv_type',
            field=models.CharField(blank=True, choices=[('calibre', 'Calibre'), ('abebooks_home_base', 'Abebooks Home Base'), ('disordine', 'Biblioteca Disordine'), ('belladonna', 'Biblioteca Belladonna'), ('eutopia', 'Eutopia')], max_length=32, null=True),
        ),
    ]
