# Generated by Django 5.0.1 on 2024-07-16 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_library_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliated_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_profiles', to='collector.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='libraries',
            field=models.ManyToManyField(related_name='affiliated_profiles', to='collector.library'),
        ),
    ]
