# Generated by Django 5.0.1 on 2024-08-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0026_library_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheetupload',
            name='csv_type',
        ),
        migrations.AddField(
            model_name='site',
            name='csv_type',
            field=models.CharField(blank=True, choices=[('calibre', 'Calibre'), ('abebooks_home_base', 'Abebooks Home Base')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheetupload',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='affiliated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_profiles', to='collector.profile'),
        ),
        migrations.AlterField(
            model_name='site',
            name='oai_metadata_format',
            field=models.CharField(blank=True, choices=[('oai_dc', 'Dublin Core'), ('marc21', 'MARC XML')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
