# Generated by Django 5.2.3 on 2025-11-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0026_remove_datasource_is_aggregation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Harvest',
        ),
    ]
