# Generated by Django 5.2.3 on 2025-12-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_delete_harvest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheetupload',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_spreadsheets', to='collector.site'),
        ),
    ]
