# Generated by Django 5.2.3 on 2025-12-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_alter_spreadsheetupload_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='internal_library_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='InternalLibraryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_library_code', models.CharField(max_length=255)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_library_codes', to='collector.library')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_library_codes', to='collector.site')),
            ],
        ),
    ]
