# Generated by Django 5.0.1 on 2024-08-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_profile_merge_and_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='affiliated_to',
        ),
    ]
