# Generated by Django 5.0.1 on 2024-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_remove_library_shared_remove_profile_affiliated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tree_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('amusewiki', 'Amusewiki'), ('generic', 'Generic OAI-PMH'), ('csv', 'CSV Upload'), ('calibretree', 'Calibre File Tree')], default='generic', max_length=32),
        ),
    ]
