# Generated by Django 5.2.3 on 2025-12-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_datasource_internal_library_code_internallibrarycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_pos', models.IntegerField(null=True)),
                ('uri', models.URLField(max_length=2048, null=True)),
                ('label', models.CharField(max_length=2048, null=True)),
                ('content_type', models.CharField(max_length=128, null=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='collector.datasource')),
            ],
        ),
    ]
