# Generated by Django 5.2.3 on 2025-12-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_datasourcelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='spip_max_ids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('amusewiki', 'Amusewiki'), ('generic', 'Generic OAI-PMH'), ('koha-marc21', 'KOHA MARC21'), ('koha-unimarc', 'KOHA UNIMARC'), ('csv', 'CSV Upload'), ('calibretree', 'Calibre File Tree'), ('spip', 'SPIP Site with meta DC fields')], default='generic', max_length=32),
        ),
    ]
