# Generated by Django 5.2.3 on 2025-12-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_datasourcelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterField(
            model_name='general',
            name='name',
            field=models.CharField(choices=[('site_name', 'Site Name'), ('site_logo', 'Site Logo'), ('site_description', 'Site Description'), ('contact_email', 'Contact Email'), ('amusewiki_doc_site', 'Amusewiki Site of Documentation')], max_length=32, unique=True),
        ),
    ]
