# Generated by Django 5.0.1 on 2024-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_site_tree_path_alter_site_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='tree_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
