# Generated by Django 5.2.3 on 2025-12-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_site_spip_max_ids_alter_site_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='spip_ignore_meta_fields',
            field=models.TextField(blank=True, help_text='One per line', null=True, verbose_name='SPIP: meta headers to ignore'),
        ),
        migrations.AlterField(
            model_name='site',
            name='spip_max_ids',
            field=models.IntegerField(blank=True, help_text='Used on the initial load. Required for SPIP', null=True, verbose_name='SPIP: Max ID'),
        ),
    ]
