# Generated by Django 5.2.3 on 2025-12-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0032_site_spip_ignore_meta_fields_alter_site_spip_max_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='spip_article_body_is_description',
            field=models.BooleanField(default=False, verbose_name='SPIP: parse the article body as item description'),
        ),
        migrations.AlterField(
            model_name='site',
            name='csv_type',
            field=models.CharField(blank=True, choices=[('calibre', 'Calibre'), ('abebooks_home_base', 'Abebooks Home Base'), ('disordine', 'Biblioteca Disordine'), ('belladonna', 'Biblioteca Belladonna'), ('eutopia', 'Eutopia')], help_text='Relevant only for CSV sites', max_length=32, null=True, verbose_name='CSV type'),
        ),
        migrations.AlterField(
            model_name='site',
            name='oai_metadata_format',
            field=models.CharField(blank=True, choices=[('oai_dc', 'Dublin Core'), ('marc21', 'MARC XML')], help_text='Relevant only for Generic OAI PHM sites', max_length=32, null=True, verbose_name='OAI-PMH metadata format'),
        ),
        migrations.AlterField(
            model_name='site',
            name='oai_set',
            field=models.CharField(blank=True, help_text='Not relevant for Amusewiki PMH and other non-PMH sites', max_length=64, null=True, verbose_name='OAI-PMH set'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tree_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calibre local path on the file system'),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
