# Generated by Django 5.2.3 on 2025-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0033_site_spip_article_body_is_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='uri',
            field=models.URLField(db_index=True, max_length=2048, null=True),
        ),
    ]
